name: CI

on:
  pull_request:
  push:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          working-directory: ./
          args: --issues-exit-code=1
          only-new-issues: false
      -
        name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          install-only: true
      -
        name: Run GoReleaser
        run: |
            make goreleaser 
        env:
          GITHUB_TOKEN: ${{ secrets.GR_TOKEN }}